/** Science quotes for the login panel. Add or remove freely — nothing else changes. */
export const quotes: [text: string, author: string][] = [
  ['Research is to see what everybody else has seen, and to think what nobody else has thought.', 'Albert Szent-Györgyi'],
  ['Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.', 'Albert Einstein'],
  ['The important thing is not to stop questioning. Curiosity has its own reason for existing.', 'Albert Einstein'],
  ["Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", 'Albert Einstein'],
  ['The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.', 'Albert Einstein'],
  ['Science is a way of thinking much more than it is a body of knowledge.', 'Albert Einstein'],
  ['We cannot solve problems with the same thinking we used to create them.', 'Albert Einstein'],
  ['The only source of knowledge is experience.', 'Albert Einstein'],
  ['Most people say that it is the intellect which makes a great scientist. They are wrong: it is character.', 'Albert Einstein'],
  ['No amount of experimentation can ever prove me right; a single experiment can prove me wrong.', 'Albert Einstein'],
  ['If I have seen further it is by standing on the shoulders of giants.', 'Isaac Newton'],
  ['I appear to have been merely like a boy playing on the shore, while the vast ocean of truth remains entirely unexplored before me.', 'Isaac Newton'],
  ['To me there has never been a higher source of earthly honor or distinction than that connected with advances in science.', 'Isaac Newton'],
  ['Gravity explains the motions of the planets, but it cannot explain who sets the planets in motion.', 'Isaac Newton'],
  ['Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.', 'Marie Curie'],
  ['I am among those who think that science has great beauty.', 'Marie Curie'],
  ['Be less curious about people and more curious about ideas.', 'Marie Curie'],
  ['Remember to look up at the stars and not down at your feet.', 'Stephen Hawking'],
  ['Science is not only a disciple of reason but, also, one of romance and passion.', 'Stephen Hawking'],
  ['We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.', 'Stephen Hawking'],
  ['Scientists have become the bearers of the torch of discovery in our quest for knowledge.', 'Stephen Hawking'],
  ['We are all now connected by the Internet, like neurons in a giant brain.', 'Stephen Hawking'],
  ['Somewhere, something incredible is waiting to be known.', 'Carl Sagan'],
  ['We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.', 'Carl Sagan'],
  ['If you wish to make an apple pie from scratch, you must first invent the universe.', 'Carl Sagan'],
  ['For small creatures such as we the vastness is bearable only through love.', 'Carl Sagan'],
  ["I would rather have questions that can't be answered than answers that can't be questioned.", 'Richard Feynman'],
  ['Philosophy of science is about as useful to scientists as ornithology is to birds.', 'Richard Feynman'],
  ['What I cannot create, I do not understand.', 'Richard Feynman'],
  ['Science is like a love affair with nature; an elusive, tantalizing mistress.', 'Richard Feynman'],
  ['Genius is one percent inspiration and ninety-nine percent perspiration.', 'Thomas Edison'],
  ["I have not failed. I've just found 10,000 ways that won't work.", 'Thomas Edison'],
  ['To invent, you need a good imagination and a pile of junk.', 'Thomas Edison'],
  ['I never did anything worth doing by accident, nor did any of my inventions come by accident; they came by work.', 'Thomas Edison'],
  ['The present is theirs; the future, for which I really worked, is mine.', 'Nikola Tesla'],
  ['Our virtues and our failures are inseparable, like force and matter. When they separate, man is no more.', 'Nikola Tesla'],
  ['The day science begins to study non-physical phenomena, it will make more progress in one decade than in all the previous centuries of its existence.', 'Nikola Tesla'],
  ['It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.', 'Charles Darwin'],
  ['Ignorance more frequently begets confidence than does knowledge.', 'Charles Darwin'],
  ['All truths are easy to understand once they are discovered; the point is to discover them.', 'Galileo Galilei'],
  ['Measure what is measurable, and make measurable what is not so.', 'Galileo Galilei'],
  ['In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.', 'Galileo Galilei'],
  ['Mathematics is the language with which God has written the universe.', 'Galileo Galilei'],
  ['Everything we call real is made of things that cannot be regarded as real.', 'Niels Bohr'],
  ['An expert is a person who has made all the mistakes that can be made in a very narrow field.', 'Niels Bohr'],
  ['It is wrong to think that the task of physics is to find out how Nature is. Physics concerns what we say about Nature.', 'Niels Bohr'],
  ['What we observe is not nature itself, but nature exposed to our method of questioning.', 'Werner Heisenberg'],
  ['The scientist only imposes two things, namely truth and sincerity, imposes them upon himself and upon other scientists.', 'Erwin Schrödinger'],
  ['Quantum physics thus reveals a basic oneness of the universe.', 'Erwin Schrödinger'],
  ['All science is either physics or stamp collecting.', 'Ernest Rutherford'],
  ['If your science experiment needs a statistician, you need to design a better experiment.', 'Ernest Rutherford'],
  ['Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world.', 'Louis Pasteur'],
  ['There are no such things as applied sciences, only applications of science.', 'Louis Pasteur'],
  ['Chemistry is necessarily an experimental science: its conclusions are drawn from data, and its principles supported by evidence from facts.', 'Michael Faraday'],
  ['The true method of scientific investigation is to begin with observation and experiment, and to end with laws and theories.', 'James Clerk Maxwell'],
  ['A scientific truth does not triumph by convincing its opponents, but rather because its opponents eventually die and a new generation grows up that is familiar with it.', 'Max Planck'],
  ['Facts are the air of scientists. Without them you can never fly.', 'Linus Pauling'],
  ['If you want to have good ideas, you must have many ideas.', 'Linus Pauling'],
  ['There is a single light of science, and to brighten it anywhere is to brighten it everywhere.', 'Isaac Asimov'],
  ['The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov'],
  ["Science literacy is the artery through which the solutions of tomorrow's problems flow.", 'Neil deGrasse Tyson'],
  ["The good thing about science is that it's true whether or not you believe in it.", 'Neil deGrasse Tyson'],
  ['Science is basically an inoculation against charlatans.', 'Neil deGrasse Tyson'],
  ['Physics is the only profession in which prophecy is not only accurate but routine.', 'Neil deGrasse Tyson'],
  ['In science, nothing is ever 100% proven.', 'Michio Kaku'],
  ['When a distinguished but elderly scientist states that something is possible, he is almost certainly right. When he states that something is impossible, he is very probably wrong.', 'Arthur C. Clarke'],
  ['Equipped with his five senses, man explores the universe around him and calls the adventure Science.', 'Edwin Hubble'],
  ['The great tragedy of science — the slaying of a beautiful hypothesis by an ugly fact.', 'Thomas Huxley'],
  ['The man of science has learned to believe in justification, not by faith, but by verification.', 'Thomas Huxley'],
  ['Science commits suicide when it adopts a creed.', 'Thomas Huxley'],
  ['Art is I; science is we.', 'Claude Bernard'],
  ['How far you go in life depends on your being tender with the young, compassionate with the aged, sympathetic with the striving and tolerant of the weak and strong.', 'George Washington Carver'],
  ['I think the most important thing is to keep active and to hope that your mind stays active.', 'Jane Goodall'],
  ['The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction.', 'Rachel Carson'],
  ['I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses.', 'Johannes Kepler'],
  ['To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.', 'Nicolaus Copernicus'],
  ['Science is a beautiful gift to humanity; we should not distort it.', 'A. P. J. Abdul Kalam'],
  ['The best brains of the nation may be found on the last benches of the classroom.', 'A. P. J. Abdul Kalam'],
  ["Without your involvement you can't succeed. With your involvement you can't fail.", 'A. P. J. Abdul Kalam'],
  ['Learning gives creativity, creativity leads to thinking, thinking provides knowledge and knowledge makes you great.', 'A. P. J. Abdul Kalam'],
  ['Great dreams of great dreamers are always transcended.', 'A. P. J. Abdul Kalam'],
  ['Success is where preparation and opportunity meets.', 'A. P. J. Abdul Kalam'],
  ['I am the master of my failure… If I never fail how will I ever learn?', 'C. V. Raman'],
  ['Success can come to you by courageous devotion to the task lying in front of you.', 'C. V. Raman'],
  ['All outstanding work, in art as well as in science, results from immense zeal applied to a great idea.', 'Santiago Ramón y Cajal'],
  ['If you know you are on the right track, if you have this inner knowledge, then nobody can turn you off — no matter what they say.', 'Barbara McClintock'],
  ["Above all, don't fear difficult moments. The best comes from them.", 'Rita Levi-Montalcini'],
  ['The reward of the young scientist is the emotional thrill of being the first person in the history of the world to see something or to understand something.', 'Cecilia Payne-Gaposchkin'],
  ['What you learn from a life in science is the vastness of our ignorance.', 'David Eagleman'],
  ['Science and everyday life cannot and should not be separated.', 'Rosalind Franklin'],
  ['When kids look up to great scientists the way they do musicians and actors, civilization will jump to the next level.', 'Brian Greene'],
  ['The science of today is the technology of tomorrow.', 'Edward Teller'],
  ['Science is organized knowledge. Wisdom is organized life.', 'Immanuel Kant'],
  ['Reason, observation, and experience; the holy trinity of science.', 'Robert Green Ingersoll'],
  ['The heart of science is measurement.', 'Erik Brynjolfsson'],
  ['Science is magic that works.', 'Kurt Vonnegut'],
  ['Science is not finished until it is communicated.', 'Mark Walport'],
  ['Science is fun. Science is curiosity. We all have natural curiosity. Science is a process of investigating.', 'Sally Ride'],
  ['Science is the acceptance of what works and the rejection of what does not. That needs more courage than we might think.', 'Jacob Bronowski'],
  ['In all science, error precedes the truth, and it is better it should go first than last.', 'Horace Walpole'],
  ['In science, the credit goes to the man who convinces the world, not to whom the idea first occurs.', 'Francis Darwin'],
  ['Science is not about absolute truths. It is about developing an understanding of the world, making predictions, and then testing these predictions.', 'Brian Schmidt'],
  ['Every great advance in science has issued from a new audacity of imagination.', 'John Dewey'],
  ['Science, my lad, is made up of mistakes, but they are mistakes which it is useful to make, because they lead little by little to the truth.', 'Jules Verne'],
  ['Scientific research is one of the most exciting and rewarding of occupations.', 'Frederick Sanger'],
  ['Everything is theoretically impossible, until it is done.', 'Robert A. Heinlein'],
  ['The virtues of science are skepticism and independence of thought.', 'Walter Gilbert'],
  ['Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it is the only thing that ever has.', 'Margaret Mead'],
  ["If you can't describe what you are doing as a process, you don't know what you're doing.", 'W. Edwards Deming'],
  ['The scientist is not a person who gives the right answers, he is one who asks the right questions.', 'Claude Lévi-Strauss'],
  ['The characteristic of scientific progress is our knowing that we did not know.', 'Gaston Bachelard'],
  ['Science is about knowing; engineering is about doing.', 'Henry Petroski'],
  ['Bad times have a scientific value. These are occasions a good learner would not miss.', 'Ralph Waldo Emerson'],
  ['True science teaches, above all, to doubt and to be ignorant.', 'Miguel de Unamuno'],
  ['Medicine is a science of uncertainty and an art of probability.', 'William Osler'],
  ['Science is exploration. The fundamental nature of exploration is that we don’t know what’s there.', 'Charles H. Townes'],
  ['Basic research is what I am doing when I don’t know what I am doing.', 'Wernher von Braun'],
  ['Physics is experience, arranged in economical order.', 'Ernst Mach'],
  ['I am now convinced that theoretical physics is actually philosophy.', 'Max Born'],
  ['What is a scientist after all? It is a curious man looking through a keyhole, the keyhole of nature, trying to know what is going on.', 'Jacques-Yves Cousteau'],
  ['The best scientist is open to experience and begins with romance — the idea that anything is possible.', 'Ray Bradbury'],
  ['A first-rate laboratory is one in which mediocre scientists can produce outstanding work.', 'Patrick M. S. Blackett'],
  ['It is strange that only extraordinary men make the discoveries, which later appear so easy and simple.', 'Georg C. Lichtenberg'],
  ['I cannot say whether things will get better if we change; what I can say is they must change if they are to get better.', 'Georg C. Lichtenberg'],
  ['In the spirit of science, there really is no such thing as a failed experiment. Any test that yields valid data is a valid test.', 'Adam Savage'],
  ['But I don’t see myself as a woman in science. I see myself as a scientist.', 'Donna Strickland'],
  ['Science and technology are going to be the basis for many of the solutions to social problems.', 'Frances Arnold'],
]

const FIVE_MINUTES = 5 * 60 * 1000

/** Same quote for everyone in a given 5-minute window, then the next one. */
export const quoteAt = (now: number) => quotes[Math.floor(now / FIVE_MINUTES) % quotes.length]

export { FIVE_MINUTES }
